### ISSUE TITLE
CommandLineTool field types become illegal after upgrading to v1.2

### ISSUE THREAD

**Issue by YuxinShi0423** [common-workflow-language/cwl-upgrader#95]
Starting from cwl v1.1, fields in ResourceRequirement of command line tool no longer accept 'string' type. However when upgrading cwl with cwl-upgrader, these fields are kept and the upgraded cwl cannot pass "cwltool --validate"

Example:
cwl code v1.0 from https://github.com/broadinstitute/cromwell/blob/32d5d0cbf07e46f56d3d070f457eaff0138478d5/centaur/src/main/resources/standardTestCases/cwl_resources/cwl_resources.cwl have fields 
```
ResourceRequirement:
      coresMin: 2
      coresMax: 2
      ramMin: 7GB
      ramMax: 7GB
```

After upgrading these fields are not fixed, so the cwl failed with "cwltool --validate":
```
* the `ramMin` field is not valid because
                                         - tried long but
                                           the value `'7GB'` is not long
                                         - tried float but
                                           the value `'7GB'` is not float or double
                                         - tried Expression but
                                           value `7GB` does not contain an expression in the form
                                           $() or ${}
```

Also, the type changes are not mentioned in the changelog from v1.0 to v1.1

Changelog: 
* v1.0: https://github.com/common-workflow-language/cwltool/blob/e37134a90ac7a7c18254e30cff16da590b45c6d7/cwltool/schemas/v1.0/CommandLineTool.yml#L944-L946
* v1.1: https://github.com/common-workflow-language/cwltool/blob/e37134a90ac7a7c18254e30cff16da590b45c6d7/cwltool/schemas/v1.1/CommandLineTool.yml#L1096-L1098
* v1.2: https://github.com/common-workflow-language/cwltool/blob/e37134a90ac7a7c18254e30cff16da590b45c6d7/cwltool/schemas/v1.2/CommandLineTool.yml#L1172-L1181

**Comment by tetron** [comment]
The "GB" suffix has never been valid in CWL.  That might work in Cromwell but it is non-standard.  The units are megabytes.  An easy way to specify gigabytes is to write `ramMin: $(7 * 1024)`.

Also, as far as I know, Cromwell does not support CWL past version 1.0.

**Comment by mr-c** [comment]
@YuxinShi0423 Thanks for your report, I was not aware of these non standard test files. If you see such syntax used in real CWL descriptions then we can teach the `cwl-upgrader` how to fix it

**Comment by YuxinShi0423** [comment]
Thanks! @tetron @mr-c I am just adding cromwell cwl tests for dxCompiler and noticed the field types have changed but not documented. Maybe the original v1.0 cwl is not runnable so it is not an issue for cwl-upgrader.

**Comment by tetron** [comment]
@YuxinShi0423 the context for accepting "string" in those fields in CWL v1.0 was a workaround to be able to accept expressions.  The specification language was later improved to be able to specify "Expression" directly, which is why it no longer includes plain "string" in the type.
